[package]
name = "integration-tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
meta-staking = { path = "../../contracts/meta-staking", version = "0.1.0", features = ["library"] }
mesh-consumer = { path = "../../contracts/mesh-consumer", version = "0.1.0", features = ["library"] }
mesh-provider = { path = "../../contracts/mesh-provider", version = "0.1.0", features = ["library"] }
cosmwasm-schema = "1.1.5"
cosmwasm-std = "1.1.5"
cosmwasm-storage = "1.1.5"
cw-storage-plus = "0.16.0"
cw2 = "0.16.0"
schemars = "0.8.11"
serde = { version = "1.0.147", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.37" }

[dev-dependencies]
cw-multi-test = "0.16.0"
